/**
 * Aegis SaaS — Multi-Channel Alert Manager
 *
 * Manages notification channel configurations per organization (Email, Slack, Discord, PagerDuty, Webhook).
 * Provides secure storage, health checking / test alerts, and reliable alert dispatching.
 */

import { getPrismaClient, isPostgresConnected } from "../saas/prisma_client.js";
import { sendAlertEmail } from "./email_service.js";

export type ChannelType =
  "email" | "slack" | "discord" | "pagerduty" | "webhook";

export interface AlertChannelConfig {
  id?: number;
  organization_id: number;
  name: string;
  type: ChannelType;
  is_enabled: boolean;
  /** Encrypted/secret config params (webhooks, routing keys, email targets) */
  config: {
    email_recipients?: string[];
    webhook_url?: string;
    pagerduty_routing_key?: string;
    custom_headers?: Record<string, string>;
  };
  created_at?: Date;
}

export interface AlertDispatchPayload {
  organization_id: number;
  anomaly_id: number;
  severity: "CRITICAL" | "HIGH" | "MEDIUM" | "LOW" | "INFO";
  title: string;
  diagnosis: string;
  z_score: number;
  source?: string;
  timestamp: string;
}

export interface DispatchResult {
  channel_id: number;
  channel_name: string;
  channel_type: ChannelType;
  success: boolean;
  error?: string;
}

// ─── Channel Testing & Dispatch ───────────────────────────────────────────────

export async function testChannel(
  channel: AlertChannelConfig,
): Promise<{ success: boolean; message: string }> {
  const testPayload: AlertDispatchPayload = {
    organization_id: channel.organization_id,
    anomaly_id: 99999,
    severity: "INFO",
    title: `[TEST] Aegis Alert Channel Verification — ${channel.name}`,
    diagnosis:
      "This is a test notification generated by Aegis SOC to verify channel connectivity.",
    z_score: 0.0,
    source: "aegis-test-runner",
    timestamp: new Date().toISOString(),
  };

  const res = await dispatchToSingleChannel(channel, testPayload);
  if (res.success) {
    return {
      success: true,
      message: `Test alert successfully sent to channel '${channel.name}'.`,
    };
  } else {
    return { success: false, message: res.error || "Test alert failed." };
  }
}

export async function dispatchToSingleChannel(
  channel: AlertChannelConfig,
  payload: AlertDispatchPayload,
): Promise<DispatchResult> {
  const result: DispatchResult = {
    channel_id: channel.id || 0,
    channel_name: channel.name,
    channel_type: channel.type,
    success: false,
  };

  try {
    switch (channel.type) {
      case "email": {
        const recipients = channel.config.email_recipients || [];
        if (recipients.length === 0)
          throw new Error("No email recipients configured.");
        for (const to of recipients) {
          await sendAlertEmail({
            to,
            orgName: `Org #${payload.organization_id}`,
            severity: payload.severity,
            title: payload.title,
            diagnosis: payload.diagnosis,
            incidentId: payload.anomaly_id,
          });
        }
        result.success = true;
        break;
      }

      case "slack":
      case "discord":
      case "webhook": {
        const webhookUrl = channel.config.webhook_url;
        if (!webhookUrl) throw new Error("Webhook URL is missing.");

        const body =
          channel.type === "slack"
            ? {
                text: `🚨 *[${payload.severity}] Aegis Alert* — ${payload.title}\n> ${payload.diagnosis}\nZ-Score: ${payload.z_score} | Anomaly ID: #${payload.anomaly_id}`,
              }
            : channel.type === "discord"
              ? {
                  content: `🚨 **[${payload.severity}] Aegis Alert** — ${payload.title}\n${payload.diagnosis}\n*Z-Score: ${payload.z_score} | ID: #${payload.anomaly_id}*`,
                }
              : payload; // raw webhook gets full payload

        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 8000);
        try {
          const resp = await fetch(webhookUrl, {
            method: "POST",
            headers: {
              "Content-Type": "application/json",
              ...channel.config.custom_headers,
            },
            body: JSON.stringify(body),
            signal: controller.signal,
          });
          if (!resp.ok)
            throw new Error(`HTTP ${resp.status} ${resp.statusText}`);
          result.success = true;
        } finally {
          clearTimeout(timeout);
        }
        break;
      }

      case "pagerduty": {
        const key = channel.config.pagerduty_routing_key;
        if (!key) throw new Error("PagerDuty routing key is missing.");

        const controller = new AbortController();
        const timeout = setTimeout(() => controller.abort(), 8000);
        try {
          const resp = await fetch("https://events.pagerduty.com/v2/enqueue", {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({
              routing_key: key,
              event_action: "trigger",
              dedup_key: `aegis-anomaly-${payload.anomaly_id}`,
              payload: {
                summary: `Aegis ${payload.severity}: ${payload.title}`,
                source: payload.source || "aegis-soc",
                severity:
                  payload.severity === "CRITICAL" ? "critical" : "warning",
                custom_details: payload,
              },
            }),
            signal: controller.signal,
          });
          if (!resp.ok) throw new Error(`PagerDuty API HTTP ${resp.status}`);
          result.success = true;
        } finally {
          clearTimeout(timeout);
        }
        break;
      }

      default:
        throw new Error(`Unsupported channel type: ${channel.type}`);
    }
  } catch (err: any) {
    result.error = err.message;
  }

  return result;
}

/**
 * Dispatch an alert to all active alert channels configured for an organization.
 */
export async function dispatchOrgAlerts(
  orgId: number,
  payload: AlertDispatchPayload,
): Promise<DispatchResult[]> {
  const results: DispatchResult[] = [];

  if (!(await isPostgresConnected())) return results;
  const prisma = getPrismaClient();

  try {
    const channels = await (prisma as any).alertChannel?.findMany({
      where: { organization_id: orgId, is_enabled: true },
    });

    if (!channels || channels.length === 0) return results;

    for (const ch of channels) {
      const config: AlertChannelConfig = {
        id: ch.id,
        organization_id: ch.organization_id,
        name: ch.name,
        type: ch.type,
        is_enabled: ch.is_enabled,
        config:
          typeof ch.config === "string" ? JSON.parse(ch.config) : ch.config,
      };

      const res = await dispatchToSingleChannel(config, payload);
      results.push(res);
    }
  } catch (err: any) {
    console.error(
      `[AlertManager] Error dispatching alerts for org ${orgId}:`,
      err.message,
    );
  }

  return results;
}
